import { Helmet } from 'react-helmet-async';

import styles from "../styles/NotFound.module.css";

function NotFound() {
    return (
        <>
            <Helmet>
                <title>페이지를 찾을 수 없습니다</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="icon.png" />
            </Helmet>

            <div className={styles.container}>

                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" className={styles['svg-icon']}>
                    <path d="m7.5 4.27 9 5.15"></path>
                    <path d="M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z"></path>
                    <path d="m3.3 7 8.7 5 8.7-5"></path>
                    <path d="M12 22V12"></path>
                </svg>

                <div>
                    <h1 className={styles.title}>
                        페이지를 찿을수 없습니다.
                    </h1>
                    <p className={styles.message}>
                        권한이 없거나 존재하지 않는 페이지입니다.
                    </p>
                </div>
            </div>

        </>
    );
}

export default NotFound;